[book]
authors = ["Aeek True"]
language = "en"
multilingual = false
src = "src"
title = "Aeek's memories"

[output.html]
no-section-label = true

[output.html.print]
enable = false

[build]
build-dir = "docs"
